export const MAX_CANDLE_HISTORY = 2000;
export const WS_RECONNECT_DELAY = 1500;
export const WS_MAX_RETRIES = 10;

export const DEFAULT_SYMBOLS = [
  'BINANCE:BTCUSDT',
  'BINANCE:ETHUSDT',
  'BINANCE:BNBUSDT',
  'BINANCE:SOLUSDT',
  'BINANCE:XRPUSDT',
  'BINANCE:DOGEUSDT',
  'BINANCE:ADAUSDT',
  'BINANCE:AVAXUSDT'
];
